import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { FALLBACK_PRICING } from "../data/fallback-pricing.js";
import { parseLitellmPricing, LITELLM_URL } from "../data/pricing-fetcher.js";
import { findPricing } from "../data/cost-calculator.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(HERE, "fixtures");
const TABLE_PATH = path.resolve(HERE, "../data/fallback-pricing.ts");

/**
 * `src/data/fallback-pricing.ts` is the offline snapshot of the LiteLLM
 * pricing feed. It went three model generations stale in silence (#82): a
 * failed fetch priced every current model at nothing, so the bar rendered a
 * confident `$0.00` that no test and no user could tell from a genuinely free
 * session.
 *
 * Regenerate with `npm run pricing`, which runs this file with
 * UPDATE_FALLBACK_PRICING=1 and rewrites the artifact instead of asserting.
 * The fetch happens ONLY under that variable — a normal `npm test` never
 * touches the network.
 *
 * The generator lives here rather than in `scripts/` so it can import the real
 * `parseLitellmPricing`. A plain-Node script cannot: `src/` uses `.js`
 * specifiers that only the bundler and vitest resolve (CLAUDE.md), so a
 * `scripts/` generator would have to reimplement the parser and could then
 * parse the feed differently from the online path — the one thing this file
 * exists to prevent.
 *
 * Staleness is caught here, by the fixtures, and at runtime by the `?` marker
 * on an unpriced cost. Deliberately NOT by a clock: an age check turns into a
 * suite failure on a day nobody touched the code, on unrelated PRs.
 */

/**
 * Every model id any fixture carries. Walks the parsed JSON rather than
 * grepping so a `"model"` substring in prose or a file path cannot masquerade
 * as a model id.
 */
function collectModelIds(value: unknown, into: Set<string>): void {
  if (Array.isArray(value)) {
    for (const item of value) collectModelIds(item, into);
    return;
  }
  if (typeof value !== "object" || value === null) return;

  for (const [key, child] of Object.entries(value)) {
    if (key === "model") {
      if (typeof child === "string") into.add(child);
      else if (typeof child === "object" && child !== null) {
        const id = (child as Record<string, unknown>)["id"];
        if (typeof id === "string") into.add(id);
      }
    }
    collectModelIds(child, into);
  }
}

function fixtureFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return fixtureFiles(full);
    return /\.jsonl?$/.test(entry.name) ? [full] : [];
  });
}

function fixtureModelIds(): string[] {
  const ids = new Set<string>();
  for (const file of fixtureFiles(FIXTURES_DIR)) {
    const raw = fs.readFileSync(file, "utf8");
    const chunks = file.endsWith(".jsonl")
      ? raw.split("\n").filter((line) => line.trim())
      : [raw];
    for (const chunk of chunks) {
      try {
        collectModelIds(JSON.parse(chunk), ids);
      } catch {
        // a fixture that is deliberately malformed carries no model id
      }
    }
  }
  return [...ids].sort();
}

function serializeTable(table: Record<string, unknown>): string {
  const header = `// Generated by \`npm run pricing\` from ${LITELLM_URL}
// Do not edit by hand — see src/__tests__/fallback-pricing.test.ts.
import type { PricingTable } from "../types/pricing.js";

/**
 * Offline snapshot of the LiteLLM pricing feed, parsed by the same
 * \`parseLitellmPricing\` the online path uses. Merged UNDER every table
 * \`fetchPricing\` returns, so a model the feed has dropped still prices.
 */
export const FALLBACK_PRICING: PricingTable = `;
  return header + JSON.stringify(table, null, 2) + ";\n";
}

if (process.env["UPDATE_FALLBACK_PRICING"]) {
  describe("fallback pricing (regenerate)", () => {
    it("rewrites the committed table from the live feed", async () => {
      const response = await fetch(LITELLM_URL, { signal: AbortSignal.timeout(30000) });
      expect(response.ok).toBe(true);
      const table = parseLitellmPricing((await response.json()) as Record<string, unknown>);
      expect(Object.keys(table).length).toBeGreaterThan(0);
      fs.writeFileSync(TABLE_PATH, serializeTable(table));
    });
  });
} else {
  describe("fallback pricing", () => {
    const ids = fixtureModelIds();

    it("harvests the model ids the fixtures actually carry", () => {
      // Guards the harvester itself: if collectModelIds silently stopped
      // finding anything, every assertion below would vacuously pass.
      expect(ids).toContain("claude-opus-5[1m]");
      expect(ids).toContain("claude-fable-5");
      expect(ids.length).toBeGreaterThanOrEqual(4);
    });

    it.each(ids)("prices %s offline", (id) => {
      expect(findPricing(id, FALLBACK_PRICING)).not.toBeNull();
    });

    it("prices the current model line", () => {
      // The fixtures pin what has been captured; these pin what is shipping.
      for (const id of ["claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5", "claude-opus-4-6"]) {
        expect(findPricing(id, FALLBACK_PRICING)).not.toBeNull();
      }
    });

    it("carries only sane rates", () => {
      expect(Object.keys(FALLBACK_PRICING).length).toBeGreaterThan(0);
      for (const [model, pricing] of Object.entries(FALLBACK_PRICING)) {
        const rates = [
          pricing.inputCostPerToken,
          pricing.outputCostPerToken,
          pricing.cacheCreationCostPerToken,
          pricing.cacheReadCostPerToken,
        ];
        for (const rate of rates) {
          expect(Number.isFinite(rate), `${model}: non-finite rate`).toBe(true);
          expect(rate, `${model}: non-positive rate`).toBeGreaterThan(0);
        }
        expect(
          pricing.outputCostPerToken,
          `${model}: output priced below input`,
        ).toBeGreaterThanOrEqual(pricing.inputCostPerToken);
        expect(
          pricing.cacheReadCostPerToken,
          `${model}: cache read priced above input`,
        ).toBeLessThanOrEqual(pricing.inputCostPerToken);
      }
    });
  });
}
